import unittest

from refind_forest.config import (
    BEGIN_MARKER,
    END_MARKER,
    INCLUDE_BLOCK,
    patch_refind_conf,
    render_theme_config,
)


class ConfigTests(unittest.TestCase):
    def test_safe_hyphenated_esp_label_scopes_filters(self) -> None:
        text = render_theme_config("a", esp_label="SAFE-LABEL")

        self.assertIn("dont_scan_dirs +,SAFE-LABEL:/EFI/Boot\n", text)
        self.assertIn("SAFE-LABEL:/EFI/ubuntu/grubx64.efi", text)
        self.assertIn("SAFE-LABEL:/EFI/ubuntu/mmx64.efi", text)

    def test_tool_row_is_defined_only_in_include_block(self) -> None:
        with self.subTest(location="include block"):
            self.assertEqual(
                INCLUDE_BLOCK,
                f"{BEGIN_MARKER}\n"
                "include theme-active.conf\n"
                "showtools windows_recovery,firmware,reboot,shutdown\n"
                f"{END_MARKER}\n",
            )
        for variant in ("a", "b"):
            with self.subTest(variant=variant):
                self.assertNotIn(
                    "showtools",
                    render_theme_config(variant, esp_label="SYSTEM"),
                )

    def test_variant_a_renders_complete_configuration(self) -> None:
        expected = (
            "# Generated by refind-forest; edit the project template, not this file.\n"
            "timeout 8\n"
            "default_selection vmlinuz\n"
            "resolution max\n"
            "scanfor internal,external\n"
            "fold_linux_kernels true\n"
            "hideui hints,arrows,badges\n"
            "banner_scale fillscreen\n"
            "banner themes/forest-a/background.png\n"
            "icons_dir themes/forest-a/icons\n"
            "selection_big themes/forest-a/selection-big.png\n"
            "selection_small themes/forest-a/selection-small.png\n"
            "dont_scan_dirs +,SYSTEM:/EFI/Boot\n"
            "dont_scan_files +,SYSTEM:/EFI/ubuntu/grubx64.efi,"
            "SYSTEM:/EFI/ubuntu/mmx64.efi\n"
        )

        self.assertEqual(render_theme_config("a", esp_label="SYSTEM"), expected)

    def test_variant_b_renders_complete_configuration(self) -> None:
        expected = (
            "# Generated by refind-forest; edit the project template, not this file.\n"
            "timeout 8\n"
            "default_selection vmlinuz\n"
            "resolution max\n"
            "scanfor internal,external\n"
            "fold_linux_kernels true\n"
            "hideui hints,arrows,badges\n"
            "banner_scale fillscreen\n"
            "banner themes/forest-b/background.png\n"
            "icons_dir themes/forest-b/icons\n"
            "selection_big themes/forest-b/selection-big.png\n"
            "selection_small themes/forest-b/selection-small.png\n"
            "dont_scan_dirs +,SYSTEM:/EFI/Boot\n"
            "dont_scan_files +,SYSTEM:/EFI/ubuntu/grubx64.efi,"
            "SYSTEM:/EFI/ubuntu/mmx64.efi\n"
        )

        self.assertEqual(render_theme_config("b", esp_label="SYSTEM"), expected)

    def test_invalid_variant_is_rejected(self) -> None:
        with self.assertRaisesRegex(ValueError, "variant must be 'a' or 'b'"):
            render_theme_config("c", esp_label="SYSTEM")

    def test_include_patch_is_idempotent(self) -> None:
        original = "timeout 20\nuse_nvram false\n"
        once = patch_refind_conf(original)
        twice = patch_refind_conf(once)
        self.assertEqual(once, twice)
        self.assertEqual(once.count(INCLUDE_BLOCK), 1)
        self.assertTrue(once.endswith(INCLUDE_BLOCK))

    def test_include_patch_replaces_existing_complete_block(self) -> None:
        original = (
            "timeout 20\n\n"
            f"{BEGIN_MARKER}\n"
            "include old-theme.conf\n"
            f"{END_MARKER}\n"
            "use_nvram false\n"
        )

        self.assertEqual(
            patch_refind_conf(original),
            "timeout 20\nuse_nvram false\n\n" + INCLUDE_BLOCK,
        )

    def test_incomplete_or_malformed_include_blocks_are_rejected(self) -> None:
        malformed = {
            "missing begin": f"{END_MARKER}\n",
            "missing end": f"{BEGIN_MARKER}\n",
            "duplicate begin": (
                f"{BEGIN_MARKER}\n{BEGIN_MARKER}\n{END_MARKER}\n"
            ),
            "duplicate end": f"{BEGIN_MARKER}\n{END_MARKER}\n{END_MARKER}\n",
            "end before begin": f"{END_MARKER}\n{BEGIN_MARKER}\n",
            "embedded explanatory comments": (
                f"# Documentation mentions {BEGIN_MARKER} here\n"
                "timeout 20\n"
                f"# Documentation mentions {END_MARKER} here\n"
            ),
            "prefixed markers": (
                f"prefix {BEGIN_MARKER}\n"
                "timeout 20\n"
                f"prefix {END_MARKER}\n"
            ),
            "suffixed markers": (
                f"{BEGIN_MARKER} extra\n"
                "timeout 20\n"
                f"{END_MARKER} extra\n"
            ),
            "indented markers": f" {BEGIN_MARKER}\n {END_MARKER}\n",
            "begin and end on same line": f"{BEGIN_MARKER} {END_MARKER}\n",
        }
        for name, text in malformed.items():
            with self.subTest(name=name):
                with self.assertRaisesRegex(
                    ValueError,
                    "incomplete Forest include block in refind.conf",
                ):
                    patch_refind_conf(text)
