"""Render Forest theme configuration without touching the ESP."""

from __future__ import annotations

BEGIN_MARKER = "# BEGIN REFIND FOREST THEME"
END_MARKER = "# END REFIND FOREST THEME"
TOOL_ROW = "showtools windows_recovery,firmware,reboot,shutdown"
INCLUDE_BLOCK = (
    f"{BEGIN_MARKER}\n"
    "include theme-active.conf\n"
    f"{TOOL_ROW}\n"
    f"{END_MARKER}\n"
)


def render_theme_config(variant: str, *, esp_label: str) -> str:
    if variant not in {"a", "b"}:
        raise ValueError("variant must be 'a' or 'b'")
    theme = f"forest-{variant}"
    lines = [
        "# Generated by refind-forest; edit the project template, not this file.",
        "timeout 8",
        "default_selection vmlinuz",
        "resolution max",
        "scanfor internal,external",
        "fold_linux_kernels true",
        "hideui hints,arrows,badges",
        "banner_scale fillscreen",
        f"banner themes/{theme}/background.png",
        f"icons_dir themes/{theme}/icons",
        f"selection_big themes/{theme}/selection-big.png",
        f"selection_small themes/{theme}/selection-small.png",
        f"dont_scan_dirs +,{esp_label}:/EFI/Boot",
        (
            "dont_scan_files +,"
            f"{esp_label}:/EFI/ubuntu/grubx64.efi,"
            f"{esp_label}:/EFI/ubuntu/mmx64.efi"
        ),
    ]
    return "\n".join(lines) + "\n"


def patch_refind_conf(text: str) -> str:
    raw_lines = text.splitlines(keepends=True)
    begin_lines = []
    end_lines = []
    for index, raw_line in enumerate(raw_lines):
        line = raw_line.removesuffix("\n").removesuffix("\r")
        if line == BEGIN_MARKER:
            begin_lines.append(index)
        elif line == END_MARKER:
            end_lines.append(index)
        elif BEGIN_MARKER in line or END_MARKER in line:
            raise ValueError("incomplete Forest include block in refind.conf")

    if (
        len(begin_lines) != len(end_lines)
        or len(begin_lines) > 1
        or (begin_lines and begin_lines[0] > end_lines[0])
    ):
        raise ValueError("incomplete Forest include block in refind.conf")
    if begin_lines:
        before = "".join(raw_lines[: begin_lines[0]])
        after = "".join(raw_lines[end_lines[0] + 1 :])
        text = before.rstrip() + "\n" + after.lstrip("\r\n")
    return text.rstrip() + "\n\n" + INCLUDE_BLOCK
